import store from '@/store';
import AlarmSettingStore from '@/store/modules/ServicesManagement/AlarmSetting/AlarmSettingStore';
import FanSpeedStore from '@/store/modules/SystemManagement/FanSpeed/FanSpeedStore';
import OperatingLogsStore from '@/store/modules/Diagnostic/OperatingLogs/OperatingLogsStore';
import PcieStore from '@/store/modules/SystemManagement/SystemInformation/PcieStore';
import ConfugureManagementStore from '@/store/modules/Settings/ConfigureManagement';
import RasLogsStore from '@/store/modules/Diagnostic/RasLogs/RasLogsStore';
import PostCodeLogsStore from '@/store/modules/Diagnostic/PostCodeLogs/PostCodeLogsStore';
import PerformanceMonitorStore from '@/store/modules/SystemManagement/PerformanceMonitor/PerformanceMonitorStore';
import SensorsStore from '@/store/modules/SystemManagement/Sensor/SensorsStore';
import PowerControlStore from '@/store/modules/SystemManagement/Power/PowerControlStore';

store.registerModule('alarmSetting', AlarmSettingStore);
store.registerModule('fanSpeed', FanSpeedStore);
store.registerModule('operatingLogs', OperatingLogsStore);
store.registerModule('pcie', PcieStore);
store.registerModule('configure', ConfugureManagementStore);
store.registerModule('rasLogs', RasLogsStore);
store.registerModule('postCodeLogs', PostCodeLogsStore);
store.registerModule('performanceMonitor', PerformanceMonitorStore);
store.registerModule('sensors', SensorsStore);
store.registerModule('powerControl', PowerControlStore);
export default store;
